config/routes.rb
Manycats::Application.routes.draw do
  resources :cat_rental_requests, only: [:index, :create]
  get 'cats/:id/request', to: 'cat_rental_requests#new', as:
    :new_cat_rental_request
  resources :cats
  post 'cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve',
    as: :approve_cat_rental_request
  post 'cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny',
    as: :deny_cat_rental_request

  resources :users, only: [:new, :create]
  resource :session

  get 'sessions', to: 'sessions#index'

  delete 'sessions/:id', to: 'sessions#destroy_other', as: :kill_session

  root to: 'cats#index'
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id         :integer          not null, primary key
#  age        :integer          not null
#  birth_date :date             not null
#  color      :string(255)      not null
#  name       :string(255)      not null
#  sex        :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Cat < ActiveRecord::Base
  validates :age, :birth_date, :color, :name, :sex, presence: true
  validates :age, :user_id, numericality: true
  validates_date :birth_date
  validates :sex, inclusion: { in: %w(M F)}
  validates :color, inclusion: { in: %w(red cream chocolate tabby calico)}

  has_many :cat_rental_requests
  belongs_to :owner, class_name: :User, foreign_key: :user_id

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :verify_cat_ownership, only: [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def new
    render :new
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render plain: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render plain: @cat.errors.full_messages
    end
  end

  private

  def cat_params
    params.require('cat').permit(:age, :name, :birth_date, :sex, :color)
  end


  def verify_cat_ownership
    @cat = Cat.find(params[:id])
    unless logged_in? && @cat.user_id == current_user.id
      flash[:errors] = ["You don't own that cat!"]
      redirect_to root_url
    end
  end

end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_for cat do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br>

  <%= f.label :birth_date %>
  <%= f.date_field :birth_date %>
  <br>

  <%= f.label :color %>
  <%= f.select :color, options_for_select(['red', 'cream', 'chocolate',             'tabby', 'calico'], selected: cat.color) %>
  <br>

  <%= f.radio_button(:sex, 'F') %>
  <%= label(:sex_F, "Female")%>

  <%= f.radio_button(:sex, 'M') %>
  <%= label(:sex_M, "Male")%>

  <%= f.submit %>

<% end %>

app/views/cats/edit.html.erb
<h1>Edit your cat!</h1>

<%= render partial: 'form', locals: {cat: @cat} %>

app/views/cats/index.html.erb
<h1>All Cats!</h1>
<% @cats.each do |cat| %>
  <ul>
    <li>Name: <%= cat.name %></li>
    <li>Age: <%= cat.age %></li>
    <li>Birth Date: <%= cat.birth_date %></li>
    <li>Color: <%= cat.color %></li>
    <li>Sex: <%= cat.sex %></li>
    <%= link_to 'View this cat!', cat_url(cat)%>
  </ul>
<% end %>

app/views/cats/new.html.erb
<h1>Create A New Cat!</h1>

<%= render partial: 'form', locals: { cat: Cat.new } %>

app/views/cats/show.html.erb
<ul>
  <li>Name: <%= @cat.name %></li>
  <li>Age: <%= @cat.age %></li>
  <li>Birth Date: <%= @cat.birth_date %></li>
  <li>Color: <%= @cat.color %></li>
  <li>Sex: <%= @cat.sex %></li>
  <%= link_to 'Rent this cat!', new_cat_rental_request_url %>
  <br>
  <br>

  <% @cat.cat_rental_requests.sort_by { |r| r.start_date }.each do |request| %>
    <%= "#{request.start_date} #{request.end_date} #{request.status} #{request.user.user_name}"%>
    <% if request.status == 'PENDING' && @cat.user_id == current_user.id %>
      <%= button_to 'Approve', approve_cat_rental_request_url(request) %>
      <%= button_to 'Deny', deny_cat_rental_request_url(request) %>
    <% end %>
    <br>
  <% end %>
</ul>